.TH "db.DB" 3 "Mon Nov 26 2018" "SimpleGraphNoSql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db.DB
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, trie)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtables\fP"
.br
.ti -1c
.RI "\fBkey_rows\fP"
.br
.ti -1c
.RI "\fBkey_cols\fP"
.br
.ti -1c
.RI "\fBsuper_key\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Cria banco de dados a partir de uma trie de tabelas
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def db\&.DB\&.__init__ ( self,  trie)"

.PP
.nf
Inicialize banco de dados com uma trie recebida
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for SimpleGraphNoSql from the source code\&.
