.TH "menus.Container" 3 "Mon Nov 26 2018" "SimpleGraphNoSql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menus.Container
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, data)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBraw_type\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBdata\fP"
.br
.ti -1c
.RI "\fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Classe representando um objeto que pode ser um Nodo ou uma Tabela ou uma Lista de celulas ou uma Celula. data representa o objeto a gerar o container

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for SimpleGraphNoSql from the source code\&.
