.TH "Tabela.RawTable" 3 "Mon Nov 26 2018" "SimpleGraphNoSql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tabela.RawTable
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, loc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBloc_source\fP"
.br
.ti -1c
.RI "\fBraw_table\fP"
.br
.ti -1c
.RI "\fBraw_sheet\fP"
.br
.ti -1c
.RI "\fBtable_label\fP"
.br
.ti -1c
.RI "\fBtable_data\fP"
.br
.ti -1c
.RI "\fBbound_x\fP"
.br
.ti -1c
.RI "\fBbound_y\fP"
.br
.ti -1c
.RI "\fBkey_cols\fP"
.br
.ti -1c
.RI "\fBkey_row\fP"
.br
.ti -1c
.RI "\fBkeys\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Classe que representa uma tabela do excel na memoria. Guarda mais dados do que o necessario e não consegue ser pickleada
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def Tabela\&.RawTable\&.__init__ ( self,  loc)"

.PP
.nf
Inicializa uma tabela a partir de um local loc
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for SimpleGraphNoSql from the source code\&.
