.TH "Tabela.Cell" 3 "Mon Nov 26 2018" "SimpleGraphNoSql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tabela.Cell
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, sheet, X, Y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdata_boundary\fP"
.br
.RI "Inicializa celula, definindo atribuitos e o tipo da celula self\&.cell_type define o tipo da variavel: Tipos possiveis: Leaf -> Representa uma celula do excel contendo dados e mais nada\&. "
.ti -1c
.RI "\fBblank_boundary\fP"
.br
.ti -1c
.RI "\fBoriginx\fP"
.br
.ti -1c
.RI "\fBoriginy\fP"
.br
.ti -1c
.RI "\fBsizex\fP"
.br
.ti -1c
.RI "\fBsizey\fP"
.br
.ti -1c
.RI "\fBx\fP"
.br
.ti -1c
.RI "\fBy\fP"
.br
.ti -1c
.RI "\fBbounds\fP"
.br
.ti -1c
.RI "\fBcell_type\fP"
.br
.ti -1c
.RI "\fBdata\fP"
.br
.ti -1c
.RI "\fBtable_label\fP"
.br
.ti -1c
.RI "\fBparent_node\fP"
.br
.ti -1c
.RI "\fBchild_nodes\fP"
.br
.ti -1c
.RI "\fBkey_row\fP"
.br
.ti -1c
.RI "\fBkey_col\fP"
.br
.ti -1c
.RI "\fBcell_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Classe que representa uma celula da tabela. Recebe um objeto do tipo sheet do xrld como entrada
    e uma posicao X referente a linha e Y referente a celula. Cria um objeto do tipo celula classificando o tipo de celula e guardando dados
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "Tabela\&.Cell\&.data_boundary"

.PP
Inicializa celula, definindo atribuitos e o tipo da celula self\&.cell_type define o tipo da variavel: Tipos possiveis: Leaf -> Representa uma celula do excel contendo dados e mais nada\&. É relacionada a duas chaves, uma de linha(key) e outra de coluna(key_col) : Key_Row -> Representa uma chave que ordena outras chaves(exemplo: ANO)\&. Uma por tabela Key_Col ->Representa uma chave que dá sentido a uma coluna\&. Podem existir varias por tabela Key -> Representa uma chave presente em uma Key_col Super_Key -> Representa uma chave que é pai de outras chaves ou de uma chave coluna\&. Label -> Representa o nome da tabela, é a raiz da arvore e pai de todos os outros nodos Merge -> Representa uma celula que foi unida uma outra celula e não tem dados Blank ->Não faz parte da tabela, dado vazio que pode ser removido sem alterações 

.SH "Author"
.PP 
Generated automatically by Doxygen for SimpleGraphNoSql from the source code\&.
