.TH "Trie.Nodo" 3 "Mon Nov 26 2018" "SimpleGraphNoSql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trie.Nodo
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, char_data, data)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchild\fP"
.br
.ti -1c
.RI "\fBparent\fP"
.br
.ti -1c
.RI "\fBchard\fP"
.br
.ti -1c
.RI "\fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Representa um nodo de uma trie
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def Trie\&.Nodo\&.__init__ ( self,  char_data,  data)"

.PP
.nf
Inicializa nodos com dados. char_data é o caractere, e data são os dados ligados aquele nodo. Representar nenhum dado como 0 
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for SimpleGraphNoSql from the source code\&.
