.TH "Trie.Trie" 3 "Mon Nov 26 2018" "SimpleGraphNoSql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Trie.Trie
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fByield_strings\fP (self, trie)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBroot\fP"
.br
.ti -1c
.RI "\fBstrings_dict\fP"
.br
.ti -1c
.RI "\fBstrings_list\fP"
.br
.ti -1c
.RI "\fBreverse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Implementa uma Trie para pesquisa no nome de tabelas de maneira eficiente
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def Trie\&.Trie\&.__init__ ( self)"

.PP
.nf
Inicializa raiz da trie como um defaultdict com uma factory de dicionarios
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for SimpleGraphNoSql from the source code\&.
